[tool.poetry]
name = "poetry-plugin-export"
version = "1.0.2"
description = "Poetry plugin to export the dependencies to various formats"
authors = ["SÃ©bastien Eustace <sebastien@eustace.io>"]
license = "MIT"
readme = "README.md"

packages = [
    { include = "poetry_plugin_export", from = "src" }
]

include = [
    { path = "tests", format = "sdist" }
]

[tool.poetry.dependencies]
python = "^3.7"
poetry = "^1.2.0b1dev0"

[tool.poetry.dev-dependencies]
pre-commit = "^2.18"
pytest = "^7.1"
pytest-mock = "^3.6.1"
poetry = {git = "https://github.com/abn/poetry.git", rev = "use-export-plugin"}
mypy = ">=0.950"

[tool.poetry.plugins."poetry.application.plugin"]
export = "poetry_plugin_export.plugins:ExportApplicationPlugin"

[tool.black]
target-version = ['py37']
preview = true

[tool.isort]
profile = "black"
force_single_line = true
atomic = true
include_trailing_comma = true
lines_after_imports = 2
lines_between_types = 1
use_parentheses = true

[tool.mypy]
show_error_codes = true
enable_error_code = ["ignore-without-code"]
strict = true
files = "src"

[[tool.mypy.overrides]]
module = [
  'cleo.*',
  'poetry.*',
  'poetry.core.*',
]
ignore_missing_imports = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
